"""Alert Engine for generating actionable alerts from liquidity analysis.

Monitors regime shifts, correlation breakdowns, and correlation surges to
generate alerts with severity levels and Discord-ready payloads.

Key features:
- Dual threshold detection (absolute + statistical deviation)
- Regime shift alerts (EXPANSION <-> CONTRACTION transitions)
- Correlation breakdown/surge alerts (major asset-liquidity relationship changes)
- Severity classification (CRITICAL, HIGH, MEDIUM, LOW)
- Discord-ready payload formatting with color coding

Anti-patterns avoided:
- DON'T alert on every fluctuation - require dual threshold
- DON'T fire alerts without previous state context
- DON'T include raw floats in Discord messages - format with 2 decimals
"""

import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any

import pandas as pd

from liquidity.analyzers.regime_classifier import RegimeResult
from liquidity.config import Settings, get_settings

logger = logging.getLogger(__name__)


class AlertType(str, Enum):
    """Type of alert generated by the engine."""

    REGIME_SHIFT = "REGIME_SHIFT"
    CORRELATION_BREAKDOWN = "CORRELATION_BREAKDOWN"
    CORRELATION_SURGE = "CORRELATION_SURGE"


class AlertSeverity(str, Enum):
    """Severity level of an alert.

    CRITICAL: Regime change + correlation breakdown together
    HIGH: Regime change OR major correlation shift
    MEDIUM: Moderate correlation change
    LOW: Minor statistical deviation
    """

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


# Discord embed colors (hex values)
SEVERITY_COLORS = {
    AlertSeverity.CRITICAL: 0xFF0000,  # Red
    AlertSeverity.HIGH: 0xFF8C00,  # Orange
    AlertSeverity.MEDIUM: 0xFFD700,  # Yellow/Gold
    AlertSeverity.LOW: 0x1E90FF,  # Dodger Blue
}


@dataclass
class Alert:
    """Alert generated by the AlertEngine.

    Attributes:
        timestamp: When the alert was generated.
        alert_type: Type of alert (REGIME_SHIFT, CORRELATION_BREAKDOWN, etc.).
        severity: Severity level (CRITICAL, HIGH, MEDIUM, LOW).
        title: Short descriptive title (e.g., "Regime Shift: EXPANSION -> CONTRACTION").
        message: Detailed description of the alert.
        asset: Asset symbol for correlation alerts (None for regime alerts).
        previous_value: Previous value (regime composite or correlation).
        current_value: Current value (regime composite or correlation).
        change: Absolute change in value.
        z_score: Statistical deviation from rolling mean (for correlation alerts).
        metadata: Additional context for Discord embed fields.
    """

    timestamp: datetime
    alert_type: AlertType
    severity: AlertSeverity
    title: str
    message: str
    asset: str | None = None
    previous_value: float | None = None
    current_value: float | None = None
    change: float | None = None
    z_score: float | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class AlertEngine:
    """Engine for generating alerts from liquidity analysis.

    Monitors:
    - Regime shifts (EXPANSION <-> CONTRACTION transitions)
    - Correlation breakdowns (large negative changes in correlation)
    - Correlation surges (large positive changes in correlation)

    Uses dual threshold detection:
    - Absolute change threshold (CORRELATION_THRESHOLD)
    - Statistical deviation threshold (SIGMA_THRESHOLD)

    Example:
        engine = AlertEngine()
        alerts = engine.check_all(
            regime=current_regime,
            correlations={"BTC": corr_series, "SPX": corr_series},
            previous_regime=previous_regime
        )
        for alert in alerts:
            payload = engine.format_discord_payload(alert)
            # Send to Discord webhook
    """

    # Thresholds for correlation shift detection
    CORRELATION_THRESHOLD = 0.3  # Absolute change threshold
    SIGMA_THRESHOLD = 2.0  # Statistical deviation threshold (z-score)
    ROLLING_WINDOW = 90  # Days for rolling mean/std calculation

    def __init__(self, settings: Settings | None = None) -> None:
        """Initialize the Alert Engine.

        Args:
            settings: Optional settings override.
        """
        self._settings = settings or get_settings()

    def check_regime_shift(
        self,
        current: RegimeResult,
        previous: RegimeResult | None,
    ) -> Alert | None:
        """Check for regime shift between current and previous classification.

        A regime shift occurs when direction changes from EXPANSION to CONTRACTION
        or vice versa. Always generates a HIGH severity alert.

        Args:
            current: Current regime classification result.
            previous: Previous regime classification result (can be None).

        Returns:
            Alert if regime shift detected, None otherwise.
        """
        if previous is None:
            logger.debug("No previous regime - cannot detect shift")
            return None

        if current.direction == previous.direction:
            logger.debug(
                "No regime shift: %s -> %s",
                previous.direction.value,
                current.direction.value,
            )
            return None

        # Regime shift detected
        title = f"Regime Shift: {previous.direction.value} -> {current.direction.value}"

        # Build detailed message
        message_parts = [
            f"Liquidity regime changed from {previous.direction.value} to {current.direction.value}.",
            "",
            "**Current State:**",
            f"- Direction: {current.direction.value}",
            f"- Intensity: {current.intensity:.1f}/100",
            f"- Confidence: {current.confidence}",
            f"- Components: {current.components}",
            "",
            "**Previous State:**",
            f"- Direction: {previous.direction.value}",
            f"- Intensity: {previous.intensity:.1f}/100",
            f"- Confidence: {previous.confidence}",
        ]
        message = "\n".join(message_parts)

        # Calculate composite values for comparison
        current_composite = (
            current.net_liq_percentile * 0.4
            + current.global_liq_percentile * 0.4
            + current.stealth_qe_score * 0.2
        )
        previous_composite = (
            previous.net_liq_percentile * 0.4
            + previous.global_liq_percentile * 0.4
            + previous.stealth_qe_score * 0.2
        )

        alert = Alert(
            timestamp=current.timestamp,
            alert_type=AlertType.REGIME_SHIFT,
            severity=AlertSeverity.HIGH,
            title=title,
            message=message,
            asset=None,
            previous_value=previous_composite,
            current_value=current_composite,
            change=current_composite - previous_composite,
            z_score=None,
            metadata={
                "previous_direction": previous.direction.value,
                "current_direction": current.direction.value,
                "intensity": current.intensity,
                "confidence": current.confidence,
                "components": current.components,
            },
        )

        logger.info(
            "Regime shift detected: %s -> %s (intensity: %.1f)",
            previous.direction.value,
            current.direction.value,
            current.intensity,
        )

        return alert

    def check_correlation_shift(
        self,
        correlations: pd.Series,
        asset: str,
    ) -> Alert | None:
        """Check for significant correlation shift in an asset-liquidity relationship.

        Uses dual threshold detection:
        1. Absolute change > CORRELATION_THRESHOLD (0.3)
        2. Statistical deviation > SIGMA_THRESHOLD (2.0 z-score)

        Either condition triggers an alert.

        Args:
            correlations: Time series of correlation values (index=dates, values=correlations).
            asset: Asset symbol (e.g., "BTC", "SPX").

        Returns:
            Alert if correlation shift detected, None otherwise.
        """
        if len(correlations) < self.ROLLING_WINDOW + 1:
            logger.debug(
                "Insufficient data for %s correlation shift detection: %d < %d",
                asset,
                len(correlations),
                self.ROLLING_WINDOW + 1,
            )
            return None

        # Get current and previous values
        current = correlations.iloc[-1]
        previous = correlations.iloc[-2]

        # Check for NaN values
        if pd.isna(current) or pd.isna(previous):
            logger.debug("NaN values in correlation series for %s", asset)
            return None

        # Calculate rolling statistics (exclude current value to avoid lookahead)
        rolling_mean = correlations.rolling(self.ROLLING_WINDOW).mean().iloc[-2]
        rolling_std = correlations.rolling(self.ROLLING_WINDOW).std().iloc[-2]

        # Check for valid rolling stats
        if pd.isna(rolling_mean) or pd.isna(rolling_std) or rolling_std <= 0:
            logger.debug("Invalid rolling statistics for %s", asset)
            return None

        # Calculate metrics
        absolute_change = current - previous
        z_score = abs(current - rolling_mean) / rolling_std

        # Determine if alert should fire (dual threshold)
        is_absolute_breach = abs(absolute_change) > self.CORRELATION_THRESHOLD
        is_statistical_breach = z_score > self.SIGMA_THRESHOLD

        if not (is_absolute_breach or is_statistical_breach):
            logger.debug(
                "No correlation shift for %s: abs_change=%.3f, z_score=%.2f",
                asset,
                absolute_change,
                z_score,
            )
            return None

        # Determine alert type and severity
        if absolute_change < -self.CORRELATION_THRESHOLD:
            alert_type = AlertType.CORRELATION_BREAKDOWN
            severity = AlertSeverity.HIGH if z_score > self.SIGMA_THRESHOLD else AlertSeverity.MEDIUM
            title = f"Correlation Breakdown: {asset}"
            direction_word = "dropped"
        elif absolute_change > self.CORRELATION_THRESHOLD:
            alert_type = AlertType.CORRELATION_SURGE
            severity = AlertSeverity.HIGH if z_score > self.SIGMA_THRESHOLD else AlertSeverity.MEDIUM
            title = f"Correlation Surge: {asset}"
            direction_word = "surged"
        else:
            # Statistical deviation without large absolute change
            alert_type = AlertType.CORRELATION_BREAKDOWN if current < rolling_mean else AlertType.CORRELATION_SURGE
            severity = AlertSeverity.MEDIUM
            title = f"Correlation Deviation: {asset}"
            direction_word = "deviated"

        # Build message
        message_parts = [
            f"{asset}-Liquidity correlation has {direction_word}.",
            "",
            f"**Current Correlation:** {current:.2f}",
            f"**Previous Correlation:** {previous:.2f}",
            f"**Change:** {absolute_change:+.2f}",
            "",
            "**Statistical Analysis:**",
            f"- Rolling Mean (90d): {rolling_mean:.2f}",
            f"- Rolling Std (90d): {rolling_std:.2f}",
            f"- Z-Score: {z_score:.2f}",
            "",
            "**Threshold Breaches:**",
            f"- Absolute: {'YES' if is_absolute_breach else 'NO'} (threshold: {self.CORRELATION_THRESHOLD:.2f})",
            f"- Statistical: {'YES' if is_statistical_breach else 'NO'} (threshold: {self.SIGMA_THRESHOLD:.1f} sigma)",
        ]
        message = "\n".join(message_parts)

        alert = Alert(
            timestamp=datetime.now(UTC),
            alert_type=alert_type,
            severity=severity,
            title=title,
            message=message,
            asset=asset,
            previous_value=previous,
            current_value=current,
            change=absolute_change,
            z_score=z_score,
            metadata={
                "rolling_mean": rolling_mean,
                "rolling_std": rolling_std,
                "is_absolute_breach": is_absolute_breach,
                "is_statistical_breach": is_statistical_breach,
            },
        )

        logger.info(
            "Correlation shift detected for %s: %.2f -> %.2f (z=%.2f)",
            asset,
            previous,
            current,
            z_score,
        )

        return alert

    def check_all(
        self,
        regime: RegimeResult,
        correlations: dict[str, pd.Series],
        previous_regime: RegimeResult | None = None,
    ) -> list[Alert]:
        """Check all conditions and return list of generated alerts.

        Checks for:
        1. Regime shift
        2. Correlation shifts for each asset

        If both regime shift AND correlation breakdown occur, the alert
        is upgraded to CRITICAL severity.

        Args:
            regime: Current regime classification result.
            correlations: Dictionary mapping asset names to correlation time series.
            previous_regime: Previous regime classification result (optional).

        Returns:
            List of Alert objects (may be empty if no alerts triggered).
        """
        alerts: list[Alert] = []

        # Check regime shift
        regime_alert = self.check_regime_shift(regime, previous_regime)
        if regime_alert:
            alerts.append(regime_alert)

        # Check correlation shifts for each asset
        correlation_alerts: list[Alert] = []
        for asset, corr_series in correlations.items():
            corr_alert = self.check_correlation_shift(corr_series, asset)
            if corr_alert:
                correlation_alerts.append(corr_alert)

        # Check for CRITICAL condition: regime shift + correlation breakdown
        if regime_alert and any(
            a.alert_type == AlertType.CORRELATION_BREAKDOWN for a in correlation_alerts
        ):
            # Upgrade regime alert to CRITICAL
            regime_alert.severity = AlertSeverity.CRITICAL
            regime_alert.title = f"CRITICAL: {regime_alert.title}"
            regime_alert.message = (
                "**WARNING: Regime shift coincides with correlation breakdown!**\n\n"
                + regime_alert.message
            )
            regime_alert.metadata["critical_trigger"] = "regime_shift_with_correlation_breakdown"
            logger.warning(
                "CRITICAL alert: regime shift with correlation breakdown"
            )

        alerts.extend(correlation_alerts)

        logger.info(
            "Alert check complete: %d alerts generated (regime=%s, correlation=%d)",
            len(alerts),
            "YES" if regime_alert else "NO",
            len(correlation_alerts),
        )

        return alerts

    def format_discord_payload(self, alert: Alert) -> dict[str, Any]:
        """Format an alert as a Discord webhook payload.

        Creates an embed with:
        - Color based on severity (red, orange, yellow, blue)
        - Title and description
        - Fields for key metrics
        - Timestamp

        Args:
            alert: Alert to format.

        Returns:
            Dictionary ready to be sent to Discord webhook.
        """
        color = SEVERITY_COLORS.get(alert.severity, 0x808080)  # Gray default

        # Build fields
        fields: list[dict[str, Any]] = []

        if alert.alert_type == AlertType.REGIME_SHIFT:
            fields.extend([
                {
                    "name": "Direction",
                    "value": f"{alert.metadata.get('previous_direction', 'N/A')} -> {alert.metadata.get('current_direction', 'N/A')}",
                    "inline": True,
                },
                {
                    "name": "Intensity",
                    "value": f"{alert.metadata.get('intensity', 0):.1f}/100",
                    "inline": True,
                },
                {
                    "name": "Confidence",
                    "value": alert.metadata.get("confidence", "N/A"),
                    "inline": True,
                },
            ])
        else:
            # Correlation alert
            if alert.asset:
                fields.append({
                    "name": "Asset",
                    "value": alert.asset,
                    "inline": True,
                })
            if alert.current_value is not None:
                fields.append({
                    "name": "Current",
                    "value": f"{alert.current_value:.2f}",
                    "inline": True,
                })
            if alert.previous_value is not None:
                fields.append({
                    "name": "Previous",
                    "value": f"{alert.previous_value:.2f}",
                    "inline": True,
                })
            if alert.change is not None:
                fields.append({
                    "name": "Change",
                    "value": f"{alert.change:+.2f}",
                    "inline": True,
                })
            if alert.z_score is not None:
                fields.append({
                    "name": "Z-Score",
                    "value": f"{alert.z_score:.2f}",
                    "inline": True,
                })

        # Add severity field
        fields.append({
            "name": "Severity",
            "value": alert.severity.value,
            "inline": True,
        })

        embed = {
            "title": alert.title,
            "description": alert.message,
            "color": color,
            "fields": fields,
            "timestamp": alert.timestamp.isoformat(),
            "footer": {
                "text": f"Global Liquidity Monitor | {alert.alert_type.value}",
            },
        }

        return {"embeds": [embed]}

    def __repr__(self) -> str:
        """Return string representation of the engine."""
        return (
            f"AlertEngine(corr_threshold={self.CORRELATION_THRESHOLD}, "
            f"sigma_threshold={self.SIGMA_THRESHOLD}, "
            f"rolling_window={self.ROLLING_WINDOW})"
        )
